language: perl
sudo: false
addons:
  apt:
    packages:
    - build-essential
    - gfortran
    - pgplot5
    - libgsl0-dev
matrix:
  include:
    # start the first coverage early so that it starts before everything else
    - perl: "5.20"
      env: COVERAGE=1
    - perl: "5.20"
      env: TEST_INSTALLED=1 # test not from blib but after installing
    - perl: "5.10"
    - perl: "blead"
    - perl: "5.26"
    - perl: "5.20"
      env: CC="clang" # use `clang` instead of `gcc` default
  allow_failures:
    - perl: blead
before_install:
  # clang is already installed in Travis-CI environment. Using PERL_MM_OPT does not work with subdirectory Makefile.PLs so we override Config.pm
  # Also, both $Config{cc} and $Config{ld} need to be set because under ELF environments (such as Travis-CI's Ubuntu), this is what Perl's Config.pm does.
  - if [ "$CC" == "clang" ]; then mkdir build_aux; echo 'package pdl_config_override; use ExtUtils::MakeMaker::Config; $Config{cc} = $Config{ld} = "clang"; 1;' >> build_aux/pdl_config_override.pm; export PERL5OPT="-I$(pwd)/build_aux -Mpdl_config_override"; fi
  # can't just PERL_MM_OPT="CCFLAGS=--coverage LDFLAGS=--coverage" because subdirs
  - if [ -n "$COVERAGE" ]; then mkdir build_aux; perl -MConfig -e 'print qq{package pdl_config_override; use ExtUtils::MakeMaker::Config; \$Config{lddlflags} = "$Config{lddlflags} --coverage"; \$Config{optimize} = "-O0 --coverage"; 1;\n}' >> build_aux/pdl_config_override.pm; export PERL5OPT="-I$(pwd)/build_aux -Mpdl_config_override"; fi
  - export PGPLOT_DEV=/NULL
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - export SPLIT_BUILD=0
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - cpanm --quiet --notest ExtUtils::F77 PGPLOT IO::All # do not need tests
  - if [ "$AUTHOR_TESTING" == 1 ]; then cpanm --quiet --notest CPAN::Changes; fi # for author tests (AUTHOR_TESTING is set to true by default by init)
  - cpanm --force --verbose ExtUtils::ParseXS # we install the latest ExtUtils::ParseXS
  - if [ "$EUMM_BLEAD" == 1 ]; then cpanm --quiet --notest --dev ExtUtils::MakeMaker; fi
  - build-dist
  - SRC_DIR=$(pwd)
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs coverage prereqs, if enabled
  - prove t/01-checkmanifest.t
  - prove -b -v $SRC_DIR/xt/00-check-changelog.t # run the author test out of the source directory
  # SYSTEM_CORES set by travis-perl-helpers
  - if [ "$SERIAL_BUILD" == 1 ]; then make; else make -j$(( $SYSTEM_CORES * 2 )); fi
before_script:
  - coverage-setup
script:
  - export PROVE_FLAG=""; if [ "$TEST_INSTALLED" == 1 ]; then make install clean; else PROVE_FLAG="-b -v"; fi # clean is to ensure no blib
  - if [ "$SERIAL_TESTING" == 1 ]; then prove $PROVE_FLAG $(test-files); else prove --formatter TAP::Formatter::File -j$(test-jobs) $PROVE_FLAG $(test-files); fi
after_success:
  - >
    if [ -n "$COVERAGE" ]; then
    for dir in $(find * -name \*.gcno | perl -pe 's#(.*)/.*#$1#'|sort -u);
    do
      cd $dir;
      perl -e 'for (@ARGV) { s/\..*//; my $f = $_; my ($r) = grep -f, map "$f.$_", qw(xs c); system "gcov $r"; }' *.gcda;
      perl -e 'for (@ARGV) { my $g = $_; s/\.gcov$//; unlink $g unless -f; }' *.gcov;
      cd $BUILD_DIR;
      gcov2perl $dir/*.gcov;
    done;
    fi
  # the gcov currently goes nuts, doesn't understand subdirs - above fixes
  - coverage-report --nogcov
branches:
  except:
    - /^wip\//
    - /^blocked/
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.perl.org#pdl"
    skip_join: true
